version: '3.8'
services:
  backend:
    build: ./backend
    container_name: django-backend
    ports:
      - "3100:3100"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    restart: always

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always 